name: bookuet
description: Book + Flower = <3

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  eva_icons_flutter: ^3.0.2
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  pdfx: ^2.6.0
  path_provider: ^2.0.8
  url_launcher: ^6.0.17

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  rename_app_plus: ^1.2.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/Domine/variable.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos.png"
  min_sdk_android: 21 # android min sdk min:16, default 21