name: bookuet
description: Book + Flower = <3

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  eva_icons_flutter: ^3.0.2
  url_launcher: ^6.0.17
  native_pdf_view: ^5.0.0
  path_provider: ^2.0.8
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Domine
      fonts:
        - asset: assets/fonts/Domine/variable.ttf
